# Copyright (c) 2026 Beasgohan-code
# Licensed under the MIT License.
# Videl Unicode Box-Drawing Table Generator Plugin

from pyrogram import filters, types
from videl import app
from videl.helpers.rich_ui import render_table


@app.on_message(filters.command(["table", "asciitable", "grid"]) & ~app.bl_users)
async def table_command(_, message: types.Message):
    if len(message.command) < 2:
        example = (
            "<b>Usage:</b>\n"
            "<code>/table Header1 | Header2 | Header3 /// Row1A | Row1B | Row1C /// Row2A | Row2B | Row2C</code>\n\n"
            "<b>Example:</b>\n"
            "<code>/table Track | Artist | Duration /// Criminal | Britney | 3:44 /// Faded | Alan Walker | 3:32</code>"
        )
        return await message.reply_text(f"📊 <b><u>Unicode Box Table Generator</u></b>\n\n{example}", quote=True)

    raw_text = message.text.split(None, 1)[1]
    sections = [s.strip() for s in raw_text.split("///") if s.strip()]

    if not sections:
        return await message.reply_text("❌ Invalid format. Separate rows with <code>///</code> and columns with <code>|</code>.", quote=True)

    header_row = [c.strip() for c in sections[0].split("|")]
    data_rows = []

    for section in sections[1:]:
        cols = [c.strip() for c in section.split("|")]
        data_rows.append(cols)

    if not data_rows:
        data_rows = [header_row]
        header_row = [f"Col {i+1}" for i in range(len(header_row))]

    table_output = render_table(header_row, data_rows, style="box")

    caption = (
        f"📊 <b><u>Formatted Unicode Table</u></b>\n\n"
        f"{table_output}\n"
        f"<i>Generated by {app.name}</i>"
    )
    await message.reply_text(caption, quote=True)
